[workspace]

members = [
    "common/directory",
    "common/hashset_delay",
    "common/lighthouse_metrics",
    "common/ionian_version",
    "common/unused_port",

    "node",
    "node/network",
    "node/rpc",
]
