[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
futures = "0.3.21"
jsonrpsee = { version = "0.11.0", features = ["full"] }
network = { path = "../network" }
serde = { version = "1.0.137", features = ["derive"] }
shared_types = { path = "../shared_types" }
task_executor = { path = "../../common/task_executor" }
tokio = { version = "1.17.0", features = ["macros", "sync"] }
tracing = "0.1.34"
