[package]
name = "shared_types"
version = "0.1.0"
edition = "2021"

[dependencies]
ethereum-types = "0.12"
eth2_ssz = "0.4.0"
eth2_ssz_derive = "0.3.0"
eth2_ssz_types = "0.2.1"
tiny-keccak = "2.0.2"
merkletree = "0.21.0"