[package]
name = "miner"
version = "0.1.0"
edition = "2021"

[dependencies]
network = { path = "../network" }
task_executor = { path = "../../common/task_executor" }
tokio = { version = "1.18.2", features = ["full"] }
tracing = "0.1.34"