network_dir = "network"
network_listen_address = "0.0.0.0"
network_libp2p_port = 1234
network_target_peers = 3
network_boot_nodes = []
network_libp2p_nodes = []
network_private = false
network_disable_discovery = false

rpc_enabled = true
rpc_listen_address = "127.0.0.1:5678"

log_config_file = "log_config"

log_contract_address = "0x532ea775ad1d08b2b3f703d87019daf94db04622"
blockchain_rpc_endpoint = "http://evmtestnet.confluxrpc.com"

